name:                demo
version:             0.1.0.0
git:                 "https://github.com/d12frosted/talks"
license:             BSD3
author:              "Boris Buliga"
maintainer:          "boris@d12frosted.io"
copyright:           "2019 Boris Buliga"

description:         Demo for 'Universe of Zippers' talk

dependencies:
- base >= 4.7 && < 5
- comonad
- rio
- text

library:
  source-dirs: src
